[tool.poetry]
name = "camerahub"
version = "0.7.0"
description = "App for cataloguing vintage cameras, lenses, films, negatives & prints"
authors = ["Jonathan Gazeley <camerahub@jonathangazeley.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://camerahub.info/"
repository = "https://github.com/djjudas21/camerahub"
packages = [
    { include = "camerahub" },
    { include = "schema" },
    { include = "help" },
]
include = [
    "static",
]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2"
pytz = "*"
django-money = "^0.15"
django-choices = "^1.7.0"
django-favicon = "^0.1.3"
psycopg2-binary = "^2.8"
django-currentuser = "^0.5"
uWSGI = "^2.0.0"
django-getenv = "^1.3.2"
django-tables2 = "^2.1.1"
django-crispy-forms = "^1.9.0"
django-autosequence = "^0"
django-sendgrid-v5 = "^0"
django-registration = "^3.0"
django-moderation = "^0.7"
django-fullurl = "^1"
django-filter = "^2.2"
awesome-slugify = "^1.6.5"
django-watson = "^1.5.5"
django-redis = "^4.11"
pylint-django = "^2.0.14"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
