apiVersion: apps/v1
kind: Deployment
metadata:
  name: photodb
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: photodb-container
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: photodb-container
    spec:
      containers:
      - image: djjudas21/photodb:latest
        imagePullPolicy: IfNotPresent
        name: photodb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: key
        - name: DB_HOST
          value: postgres-service
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: photodb-config
              key: db_name
        - name: DB_PORT
          value: '5432'
        - name: DB_ENGINE
          value: django.db.backends.postgresql
        - name: DJANGO_PROD
          value: 'true'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30