# Credentials for Postgres database
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  user: cGhvdG9kYg==
  password: cGhvdG9kYg==
---
# Secret for Django
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
data:
  key: cGhvdG9kYg==
---
# TLS/SSL certs
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: photodb
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: myingress.com
    http:
      paths:
      - path: /
        backend:
          serviceName: photodb
          servicePort: 8000
  tls:
  - hosts:
    - myingress.com
    secretName: photodb-ingress-cert
