---
# TLS/SSL certs
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camerahub
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: testing.camerahub.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: camerahub
                port:
                  number: 8000
  tls:
    - hosts:
        - testing.camerahub.info
      secretName: camerahub-preprod-ingress-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camerahub
spec:
  replicas: 1
