---
# TLS/SSL certs
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camerahub
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: testing.camerahub.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: camerahub
                port:
                  number: 8000
  tls:
    - hosts:
        - testing.camerahub.info
      secretName: camerahub-preprod-ingress-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camerahub
spec:
  replicas: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  storageClassName: freenas-nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
spec:
  storageClassName: freenas-nfs-csi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        storageClassName: freenas-nfs-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
spec:
  volumeClaimTemplates:
    - metadata:
        name: postgres-replica
      spec:
        storageClassName: freenas-nfs-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: freenas-nfs-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
