# TLS/SSL certs
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: camerahub
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: chub.jonathangazeley.com
      http:
        paths:
          - path: /
            backend:
              serviceName: camerahub
              servicePort: 8000
  tls:
    - hosts:
        - chub.jonathangazeley.com
      secretName: camerahub-preprod-ingress-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camerahub
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: djjudas21/camerahub:0.4.0
          name: camerahub
