---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camerahub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: camerahub
                port:
                  number: 8000
