apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: camerahub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: camerahub
              servicePort: 8000
            path: /
