# Secret for Django
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
data:
  key: cGhvdG9kYg==
---
# Credentials for Postgres database
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  user: cGhvdG9kYg==
  password: cGhvdG9kYg==
