---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./camerahub
  - ./postgres
  - ./redis

secretGenerator:
  - name: camerahub-secret
    env: camerahub-secret.env
    behavior: merge

configMapGenerator:
  - name: camerahub-config
    env: camerahub-config.env
    behavior: merge
