apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  CAMERAHUB_DB_USER: {{ .Values.global.postgresql.username }}
  CAMERAHUB_DB_NAME: {{ .Values.global.postgresql.database }}
  CAMERAHUB_PROD: "{{ .Values.camerahub.production }}"
