{{- if .Values.ingress.enabled -}}
{{- $fullName := include "camerahub.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "camerahub.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.camerahub.domain | quote }}
        secretName: ingress-tls
  {{- end }}
  rules:
    - host: {{ .Values.camerahub.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-app
                port:
                  number: {{ $svcPort }}
  {{- end }}
