apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  CAMERAHUB_SECRET_KEY: {{ .Values.camerahub.secretKey | b64enc }}
  CAMERAHUB_DB_PASS: {{ .Values.global.postgresql.password | b64enc }}
  CAMERAHUB_ADMIN_EMAIL: {{ .Values.camerahub.adminEmail | b64enc }}
  CAMERAHUB_ADMIN_PASSWORD: {{ .Values.camerahub.adminPassword | b64enc }}
