apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  CAMERAHUB_SECRET_KEY: {{ .Values.camerahub.secretKey | b64enc }}
  {{- if .Values.postgresql.enabled }}
  CAMERAHUB_DB_PASS: {{ .Values.global.postgresql.auth.password | b64enc }}
  {{- else }}
  CAMERAHUB_DB_PASS: {{ .Values.camerahub.database.password | b64enc }}
  {{- end }}
  {{- if .Values.camerahub.adminEmail }}
  CAMERAHUB_ADMIN_EMAIL: {{ .Values.camerahub.adminEmail | b64enc }}
  {{- end }}
  {{- if .Values.camerahub.adminPassword }}
  CAMERAHUB_ADMIN_PASSWORD: {{ .Values.camerahub.adminPassword | b64enc }}
  {{- end }}
  {{- if .Values.camerahub.email.sendgridKey }}
  CAMERAHUB_SENDGRID_KEY: {{ .Values.camerahub.email.sendgridKey | b64enc }}
  {{- end }}
  {{- if .Values.camerahub.email.password }}
  CAMERAHUB_EMAIL_HOST_PASSWORD: {{ .Values.camerahub.email.password | b64enc }}
  {{- end }}
