apiVersion: v1
kind: Service
metadata:
  name: {{ include "camerahub.fullname" . }}-app
  labels:
    {{- include "camerahub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "camerahub.selectorLabels" . | nindent 4 }}
