apiVersion: v1
kind: Service
metadata:
  name: {{ include "camerahub.fullname" . }}-static
  labels:
    app: static
spec:
  type: {{ .Values.static.service.type }}
  ports:
    - port: {{ .Values.static.service.port }}
      protocol: TCP
      name: http
  selector:
    app: static
