apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: photodb
  name: photodb
  selfLink: /api/v1/namespaces/photodb/services/photodb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: photodb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
