from django.urls import path

from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('accessory/', views.AccessoryList.as_view(), name='accessory-list'),
  path('archive/', views.ArchiveList.as_view(), name='archive-list'),
  path('battery/', views.BatteryList.as_view(), name='battery-list'),
  path('bulkfilm/', views.BulkFilmList.as_view(), name='bulkfilm-list'),
  path('camera/', views.CameraList.as_view(), name='camera-list'),
  path('camera/<int:pk>', views.CameraDetail.as_view(), name='camera-detail'),
  path('camera/create/', views.CameraCreate.as_view(), name='camera-create'),
  path('camera/<int:pk>/update', views.CameraUpdate.as_view(), name='camera-update'),
  path('cameramodel/', views.CameraModelList.as_view(), name='cameramodel-list'),
  path('developer/', views.DeveloperList.as_view(), name='developer-list'),
  path('enlarger/', views.EnlargerList.as_view(), name='enlarger-list'),
  path('filmstock/', views.FilmStockList.as_view(), name='filmstock-list'),
  path('filter/', views.FilterList.as_view(), name='filter-list'),
  path('flash/', views.FlashList.as_view(), name='flash-list'),
  path('flashprotocol/', views.FlashProtocolList.as_view(), name='flashprotocol-list'),
  path('format/', views.FormatList.as_view(), name='format-list'),
  path('lens/', views.LensList.as_view(), name='lens-list'),
  path('lensmodel/', views.LensModelList.as_view(), name='lensmodel-list'),
  path('manufacturer/', views.ManufacturerList.as_view(), name='manufacturer-list'),
  path('meteringtype/', views.MeteringTypeList.as_view(), name='meteringtype-list'),
  path('mount/', views.MountList.as_view(), name='mount-list'),
  path('mountadapter/', views.MountAdapterList.as_view(), name='mountadapter-list'),
  path('negativesize/', views.NegativeSizeList.as_view(), name='negativesize-list'),
  path('order/', views.OrderList.as_view(), name='order-list'),
  path('paperstock/', views.PaperStockList.as_view(), name='paperstock-list'),
  path('person/', views.PersonList.as_view(), name='person-list'),
  path('print/', views.PrintList.as_view(), name='print-list'),
  path('process/', views.ProcessList.as_view(), name='process-list'),
  path('repair/', views.RepairList.as_view(), name='repair-list'),
  path('scan/', views.ScanList.as_view(), name='scan-list'),
  path('negative/', views.NegativeList.as_view(), name='negative-list'),
  path('film/', views.FilmList.as_view(), name='film-list'),
  path('series/', views.SeriesList.as_view(), name='series-list'),
  path('teleconverter/', views.TeleconverterList.as_view(), name='teleconverter-list'),
  path('toner/', views.TonerList.as_view(), name='toner-list'),
]