# Generated by Django 2.1.10 on 2019-08-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=45, unique=True, verbose_name='Name of the manufacturer')),
                ('city', models.CharField(max_length=45, verbose_name='City in which the manufacturer is based')),
                ('country', models.CharField(max_length=45, verbose_name='Country in which the manufacturer is based')),
                ('url', models.URLField(max_length=45, verbose_name='URL to the manufacturers main website')),
                ('founded', models.DateField(verbose_name='Year in which the manufacturer was founded')),
                ('dissolved', models.DateField(verbose_name='Year in which the manufacturer was dissolved')),
            ],
        ),
    ]
