# Generated by Django 2.1.10 on 2019-08-13 14:11

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop),
    ]
