# Generated by Django 5.0.1 on 2024-01-08 13:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='colour',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Colour of the filter', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
