# Generated by Django 3.2.13 on 2022-05-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_squashed_0133_auto_20220524_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='enlargermodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='filmstock',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='flashmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lensmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='mount',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='paperstock',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='teleconvertermodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='tags',
        ),
    ]
