# Generated by Django 2.1.10 on 2019-08-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer',
            new_name='name',
        ),
    ]
