# Generated by Django 2.1.10 on 2019-08-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20190812_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=45, verbose_name='Model of the accessory')),
                ('acquired', models.DateField(verbose_name='Date that this accessory was acquired')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Purchase cost of the accessory')),
                ('lost', models.DateField(verbose_name='Date that this accessory was lost')),
                ('lost_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sale price of the accessory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, unique=True, verbose_name='Type of accessory')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.AccessoryType'),
        ),
    ]
