# Generated by Django 2.1.10 on 2019-08-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Archive'),
        ),
        migrations.AlterField(
            model_name='film',
            name='bulk_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.BulkFilm'),
        ),
        migrations.AlterField(
            model_name='film',
            name='bulk_film_loaded',
            field=models.DateField(blank=True, null=True, verbose_name='Date that this film was cut from a bulk roll'),
        ),
        migrations.AlterField(
            model_name='film',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Camera'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_loaded',
            field=models.DateField(blank=True, null=True, verbose_name='Date when the film was loaded into a camera'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_processed',
            field=models.DateField(blank=True, null=True, verbose_name='Date when the film was processed'),
        ),
        migrations.AlterField(
            model_name='film',
            name='dev_n',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of the Push/Pull rating of the film, e.g. N+1, N-2'),
        ),
        migrations.AlterField(
            model_name='film',
            name='dev_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Temperature of development'),
        ),
        migrations.AlterField(
            model_name='film',
            name='dev_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration of development'),
        ),
        migrations.AlterField(
            model_name='film',
            name='dev_uses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of previous uses of the developer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Developer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='development_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Extra freeform notes about the development process'),
        ),
        migrations.AlterField(
            model_name='film',
            name='directory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the directory that contains the scanned images from this film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date of the film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='exposed_at',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISO at which the film was exposed'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_batch',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Batch number of the film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='frames',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expected (not actual) number of frames from the film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price paid for this film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='processed_by',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Person or place that processed this film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date this film was purchased'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title of the film'),
        ),
    ]
