# Generated by Django 2.1.11 on 2019-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20190819_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='accessorytype',
            options={'verbose_name_plural': 'Accessory types'},
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name_plural': 'Archives'},
        ),
        migrations.AlterModelOptions(
            name='archivetype',
            options={'verbose_name_plural': 'Archive types'},
        ),
        migrations.AlterModelOptions(
            name='battery',
            options={'verbose_name_plural': 'Batteries'},
        ),
        migrations.AlterModelOptions(
            name='bodytype',
            options={'verbose_name_plural': 'Body types'},
        ),
        migrations.AlterModelOptions(
            name='bulkfilm',
            options={'verbose_name_plural': 'Bulk films'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterModelOptions(
            name='cameramodel',
            options={'verbose_name_plural': 'Camera models'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='enlarger',
            options={'verbose_name_plural': 'Enlargers'},
        ),
        migrations.AlterModelOptions(
            name='exposureprogram',
            options={'verbose_name_plural': 'Exposure programs'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='filmstock',
            options={'verbose_name_plural': 'Film stocks'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name_plural': 'Filters'},
        ),
        migrations.AlterModelOptions(
            name='filteradapter',
            options={'verbose_name_plural': 'Filter adapters'},
        ),
        migrations.AlterModelOptions(
            name='flash',
            options={'verbose_name_plural': 'Flashes'},
        ),
        migrations.AlterModelOptions(
            name='flashprotocol',
            options={'verbose_name_plural': 'Flash protocols'},
        ),
        migrations.AlterModelOptions(
            name='focustype',
            options={'verbose_name_plural': 'Focus types'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name_plural': 'Formats'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'Lenses'},
        ),
        migrations.AlterModelOptions(
            name='lensmodel',
            options={'verbose_name_plural': 'Lens models'},
        ),
        migrations.AlterModelOptions(
            name='lightmeter',
            options={'verbose_name_plural': 'Light meters'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='meteringmode',
            options={'verbose_name_plural': 'Metering modes'},
        ),
        migrations.AlterModelOptions(
            name='meteringtype',
            options={'verbose_name_plural': 'Metering types'},
        ),
        migrations.AlterModelOptions(
            name='mount',
            options={'verbose_name_plural': 'Mounts'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='negative',
            options={'verbose_name_plural': 'Negatives'},
        ),
        migrations.AlterModelOptions(
            name='negativesize',
            options={'verbose_name_plural': 'Negative sizes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='paperstock',
            options={'verbose_name_plural': 'Paper stocks'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='print',
            options={'verbose_name_plural': 'Prints'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='projector',
            options={'verbose_name_plural': 'Projectors'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name_plural': 'Repairs'},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name_plural': 'Scans'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='shutterspeed',
            options={'verbose_name_plural': 'Shutter speeds'},
        ),
        migrations.AlterModelOptions(
            name='shuttertype',
            options={'verbose_name_plural': 'Shutter types'},
        ),
        migrations.AlterModelOptions(
            name='teleconverter',
            options={'verbose_name_plural': 'Teleconverters'},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={'verbose_name_plural': 'Toners'},
        ),
    ]
