# Generated by Django 2.1.10 on 2019-08-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20190812_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name of this archive')),
                ('max_width', models.IntegerField(verbose_name='Maximum width of media that this archive can store')),
                ('max_height', models.IntegerField(verbose_name='Maximum height of media that this archive can store')),
                ('location', models.CharField(max_length=45, verbose_name='Location of this archive')),
                ('storage', models.CharField(max_length=45, verbose_name='The type of storage used for this archive, e.g. box, folder, ringbinder, etc')),
                ('sealed', models.BooleanField(default=0, verbose_name='Whether or not this archive is sealed (closed to new additions)')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, verbose_name='Name of this type of archive')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Common name of the battery')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nominal voltage of the battery')),
                ('chemistry', models.CharField(max_length=45, verbose_name='Battery chemistry (e.g. Alkaline, Lithium, etc)')),
                ('other_names', models.CharField(max_length=45, verbose_name='Alternative names for this kind of battery')),
            ],
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, unique=True, verbose_name='Name of camera body type (e.g. SLR, compact, etc)')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.ArchiveType'),
        ),
    ]
