# Generated by Django 2.1.10 on 2019-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_auto_20190813_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramodel',
            name='x_sync',
        ),
        migrations.RemoveField(
            model_name='exposureprogram',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meteringmode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meteringtype',
            name='id',
        ),
        migrations.AddField(
            model_name='cameramodel',
            name='exposure_programs',
            field=models.ManyToManyField(to='schema.ExposureProgram'),
        ),
        migrations.AddField(
            model_name='cameramodel',
            name='metering_modes',
            field=models.ManyToManyField(to='schema.MeteringMode'),
        ),
        migrations.AddField(
            model_name='cameramodel',
            name='shutter_speeds',
            field=models.ManyToManyField(to='schema.ShutterSpeed'),
        ),
        migrations.AlterField(
            model_name='exposureprogram',
            name='name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Name of exposure program as defined by EXIF tag ExposureProgram'),
        ),
        migrations.AlterField(
            model_name='meteringmode',
            name='name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Name of metering mode as defined by EXIF tag MeteringMode'),
        ),
        migrations.AlterField(
            model_name='meteringtype',
            name='name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Name of the metering technology (e.g. Selenium)'),
        ),
    ]
