# Generated by Django 2.2.4 on 2019-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_shutter_speeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='dissolved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year in which the manufacturer was dissolved'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year in which the manufacturer was founded'),
        ),
    ]
