# Generated by Django 2.1.10 on 2019-08-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_auto_20190813_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlarger',
            old_name='negative_size_id',
            new_name='negative_size',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='archive_id',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='filmstock',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='lens',
            old_name='lensmodel_id',
            new_name='lensmodel',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='camera_id',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='filmstock_id',
            new_name='filmstock',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='format_id',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='lens_id',
            new_name='lens',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='negative',
            old_name='photographer_id',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='negative_id',
            new_name='negative',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='print_id',
            new_name='print',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='archive_id',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='developer_id',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='enlarger_id',
            new_name='enlarger',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='lens_id',
            new_name='lens',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='printer_id',
            new_name='printer',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='toner_id',
            new_name='toner',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='negative_id',
            new_name='negative',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='print_id',
            new_name='print',
        ),
    ]
