# Generated by Django 2.2.4 on 2019-09-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0012_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Camera', 'Camera'), ('Enlarger', 'Enlarger'), ('Projector', 'Projector'), ('Telescope', 'Telescope'), ('Microscope', 'Microscope')], max_length=15, null=True, verbose_name='The intended purpose of this lens mount'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='type',
            field=models.CharField(blank=True, choices=[('Bayonet', 'Bayonet'), ('Screw', 'Screw'), ('Friction', 'Friction fit'), ('Lens board', 'Lens board')], max_length=15, null=True, verbose_name='The physical mount type of this lens mount'),
        ),
    ]
