# Generated by Django 2.2.4 on 2019-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0013_auto_20190902_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='digital_only',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Whether this mount is intended only for digital cameras'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='shutter_in_lens',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Whether this lens mount system incorporates the shutter into the lens'),
        ),
    ]
