# Generated by Django 2.2.4 on 2019-09-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0014_auto_20190902_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mount',
            name='fixed',
        ),
    ]
