# Generated by Django 2.2.4 on 2019-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0015_remove_mount_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='type',
            field=models.CharField(blank=True, choices=[('Bayonet', 'Bayonet'), ('Breech lock', 'Breech lock'), ('Screw', 'Screw'), ('Friction', 'Friction fit'), ('Lens board', 'Lens board')], max_length=15, null=True, verbose_name='The physical mount type of this lens mount'),
        ),
    ]
