# Generated by Django 2.2.4 on 2019-09-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0020_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type',
            field=models.CharField(choices=[('Battery grip', 'Battery grip'), ('Case', 'Case'), ('Film back', 'Film back'), ('Focusing screen', 'Focusing screen'), ('Lens hood', 'Lens hood'), ('Lens cap', 'Lens cap'), ('Power winder', 'Power winder'), ('Viewfinder', 'Viewfinder'), ('Rangefinder', 'Rangefinder')], help_text='Type of accessory', max_length=15),
        ),
        migrations.DeleteModel(
            name='AccessoryType',
        ),
    ]