# Generated by Django 2.2.4 on 2019-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0021_auto_20190906_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='storage',
            field=models.CharField(blank=True, choices=[('Ringbinder', 'Ringbinder'), ('Folder', 'Folder'), ('Box', 'Box'), ('Portfolio', 'Portfolio'), ('Slide tray', 'Slide tray')], help_text='The type of storage used for this archive', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='type',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Slide', 'Slide'), ('Print', 'Print')], help_text='What is stored in this archive?', max_length=8),
        ),
        migrations.AlterField(
            model_name='cameramodel',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Box camera', 'Box camera'), ('Folding camera', 'Folding camera'), ('Compact camera', 'Compact camera'), ('SLR', 'SLR'), ('TLR', 'TLR'), ('Bridge camera', 'Bridge camera'), ('View camera', 'View camera'), ('Pistol grip camera', 'Pistol grip camera'), ('Miniature camera', 'Miniature camera')], help_text='Body type of this camera model', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cameramodel',
            name='focus_type',
            field=models.CharField(blank=True, choices=[('Autofocus', 'Autofocus'), ('Fixed focus', 'Fixed focus'), ('Zone focus', 'Zone focus'), ('Rangefinder', 'Rangefinder'), ('SLR', 'SLR'), ('TLR', 'TLR'), ('View camera', 'View camera')], help_text='Focus type used on this camera model', max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='ArchiveType',
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='FocusType',
        ),
    ]
