# Generated by Django 2.2.4 on 2019-09-18 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0024_auto_20190911_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negative',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the location where the picture was taken', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='negative',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the location where the picture was taken', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='print',
            name='filtration_grade',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Contrast grade of paper used', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
