# Generated by Django 2.2.4 on 2019-09-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0025_auto_20190918_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='Lens attached to this camera, if it is a fixed-lens camera', limit_choices_to={'lensmodel__fixed_mount': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Lens'),
        ),
        migrations.AlterField(
            model_name='cameramodel',
            name='lensmodel',
            field=models.ForeignKey(blank=True, help_text='Lens model attached to this camera model, if it is a fixed-lens camera', limit_choices_to={'fixed_mount': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.LensModel'),
        ),
        migrations.AlterField(
            model_name='cameramodel',
            name='mount',
            field=models.ForeignKey(blank=True, help_text='Lens mount used by this camera model', limit_choices_to={'purpose': 'Camera'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Mount'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='Camera used to shoot this movie', limit_choices_to={'movie': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Camera'),
        ),
        migrations.AlterField(
            model_name='print',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='Enlarger lens used to make this print', limit_choices_to={'mount__purpose': 'Enlarger'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Lens'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='mount',
            field=models.ForeignKey(blank=True, help_text='Lens mount used by this projector', limit_choices_to={'purpose': 'Projector'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Mount'),
        ),
        migrations.AlterField(
            model_name='teleconverter',
            name='mount',
            field=models.ForeignKey(blank=True, help_text='Lens mount used by this teleconverter', limit_choices_to={'purpose': 'Camera'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Mount'),
        ),
    ]
