# Generated by Django 2.2.4 on 2019-09-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0026_auto_20190918_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='developer',
            field=models.ForeignKey(blank=True, help_text='Developer used to develop this film', limit_choices_to={'for_film': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Developer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Person or place that processed this film', null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Person'),
        ),
        migrations.AlterField(
            model_name='print',
            name='developer',
            field=models.ForeignKey(blank=True, help_text='Developer used to develop this print', limit_choices_to={'for_paper': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Developer'),
        ),
    ]
