# Generated by Django 2.2.4 on 2019-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0029_auto_20190918_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='type',
            field=models.CharField(blank=True, choices=[('Bayonet', 'Bayonet'), ('Breech lock', 'Breech lock'), ('Screw', 'Screw'), ('Friction', 'Friction'), ('Lens board', 'Lens board')], help_text='The physical mount type of this lens mount', max_length=15, null=True),
        ),
    ]
