# Generated by Django 2.2.4 on 2019-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0030_auto_20190918_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutterspeed',
            name='duration',
            field=models.DecimalField(decimal_places=5, help_text='Shutter speed in decimal notation, e.g. 0.04', max_digits=9),
        ),
    ]
