# Generated by Django 2.2.4 on 2019-09-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0031_auto_20190919_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['name'], 'verbose_name_plural': 'Archives'},
        ),
        migrations.AlterModelOptions(
            name='battery',
            options={'ordering': ['name'], 'verbose_name_plural': 'Batteries'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['cameramodel__manufacturer', 'cameramodel__model', 'serial'], 'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterModelOptions(
            name='cameramodel',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Camera models'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='enlarger',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Enlargers'},
        ),
        migrations.AlterModelOptions(
            name='filmstock',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'Film stocks'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['thread', 'type'], 'verbose_name_plural': 'Filters'},
        ),
        migrations.AlterModelOptions(
            name='filteradapter',
            options={'ordering': ['camera_thread', 'filter_thread'], 'verbose_name_plural': 'Filter adapters'},
        ),
        migrations.AlterModelOptions(
            name='flash',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Flashes'},
        ),
        migrations.AlterModelOptions(
            name='flashprotocol',
            options={'ordering': ['name'], 'verbose_name_plural': 'Flash protocols'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'ordering': ['format'], 'verbose_name_plural': 'Formats'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'ordering': ['lensmodel__manufacturer', 'lensmodel__model', 'serial'], 'verbose_name_plural': 'Lenses'},
        ),
        migrations.AlterModelOptions(
            name='lensmodel',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Lens models'},
        ),
        migrations.AlterModelOptions(
            name='lightmeter',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Light meters'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='mount',
            options={'ordering': ['mount'], 'verbose_name_plural': 'Mounts'},
        ),
        migrations.AlterModelOptions(
            name='negative',
            options={'ordering': ['film', 'frame'], 'verbose_name_plural': 'Negatives'},
        ),
        migrations.AlterModelOptions(
            name='negativesize',
            options={'ordering': ['area'], 'verbose_name_plural': 'Negative sizes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['added'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='paperstock',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'Paper stocks'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['name'], 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='projector',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Projectors'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['date'], 'verbose_name_plural': 'Repairs'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='shutterspeed',
            options={'ordering': ['duration'], 'verbose_name_plural': 'Shutter speeds'},
        ),
        migrations.AlterModelOptions(
            name='teleconverter',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'Teleconverters'},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'Toners'},
        ),
    ]
