# Generated by Django 2.2.4 on 2019-09-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0032_auto_20190919_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'accessories'},
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['name'], 'verbose_name_plural': 'archives'},
        ),
        migrations.AlterModelOptions(
            name='battery',
            options={'ordering': ['name'], 'verbose_name_plural': 'batteries'},
        ),
        migrations.AlterModelOptions(
            name='bulkfilm',
            options={'verbose_name_plural': 'bulk films'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['cameramodel__manufacturer', 'cameramodel__model', 'serial'], 'verbose_name_plural': 'cameras'},
        ),
        migrations.AlterModelOptions(
            name='cameramodel',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'camera models'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'conditions'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'developers'},
        ),
        migrations.AlterModelOptions(
            name='enlarger',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'enlargers'},
        ),
        migrations.AlterModelOptions(
            name='exposureprogram',
            options={'verbose_name_plural': 'exposure programs'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': 'films'},
        ),
        migrations.AlterModelOptions(
            name='filmstock',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'film stocks'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['thread', 'type'], 'verbose_name_plural': 'filters'},
        ),
        migrations.AlterModelOptions(
            name='filteradapter',
            options={'ordering': ['camera_thread', 'filter_thread'], 'verbose_name_plural': 'filter adapters'},
        ),
        migrations.AlterModelOptions(
            name='flash',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'flashes'},
        ),
        migrations.AlterModelOptions(
            name='flashprotocol',
            options={'ordering': ['name'], 'verbose_name_plural': 'flash protocols'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'ordering': ['format'], 'verbose_name_plural': 'formats'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'ordering': ['lensmodel__manufacturer', 'lensmodel__model', 'serial'], 'verbose_name_plural': 'lenses'},
        ),
        migrations.AlterModelOptions(
            name='lensmodel',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'lens models'},
        ),
        migrations.AlterModelOptions(
            name='lightmeter',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'light meters'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name_plural': 'manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='meteringmode',
            options={'verbose_name_plural': 'metering modes'},
        ),
        migrations.AlterModelOptions(
            name='meteringtype',
            options={'verbose_name_plural': 'metering types'},
        ),
        migrations.AlterModelOptions(
            name='mount',
            options={'ordering': ['mount'], 'verbose_name_plural': 'mounts'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='negative',
            options={'ordering': ['film', 'frame'], 'verbose_name_plural': 'negatives'},
        ),
        migrations.AlterModelOptions(
            name='negativesize',
            options={'ordering': ['area'], 'verbose_name_plural': 'negative sizes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['added'], 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='paperstock',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'paper stocks'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='print',
            options={'verbose_name_plural': 'prints'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['name'], 'verbose_name_plural': 'processes'},
        ),
        migrations.AlterModelOptions(
            name='projector',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'projectors'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['date'], 'verbose_name_plural': 'repairs'},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name_plural': 'scans'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='shutterspeed',
            options={'ordering': ['duration'], 'verbose_name_plural': 'shutter speeds'},
        ),
        migrations.AlterModelOptions(
            name='teleconverter',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name_plural': 'teleconverters'},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name_plural': 'toners'},
        ),
    ]
