# Generated by Django 2.2.4 on 2019-09-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0033_auto_20190919_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='bleach_time',
        ),
        migrations.RemoveField(
            model_name='print',
            name='toner_dilution',
        ),
        migrations.RemoveField(
            model_name='print',
            name='toner_time',
        ),
        migrations.RemoveField(
            model_name='print',
            name='toner',
        ),
        migrations.CreateModel(
            name='Toning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilution', models.CharField(blank=True, help_text='Dilution of the toner', max_length=8, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Duration of the toning', null=True)),
                ('order', models.PositiveIntegerField(blank=True, help_text='Order in which this toner was applied', null=True)),
                ('print', models.ForeignKey(help_text='Print that was toned', on_delete=django.db.models.deletion.CASCADE, to='schema.Print')),
                ('toner', models.ForeignKey(help_text='Toner used on this print', on_delete=django.db.models.deletion.CASCADE, to='schema.Toner')),
            ],
        ),
        migrations.AddField(
            model_name='print',
            name='toner',
            field=models.ManyToManyField(help_text='Toners and bleaches used to treat this print', through='schema.Toning', to='schema.Toner'),
        ),
    ]
