# Generated by Django 2.2.4 on 2019-09-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0034_auto_20190920_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='Enlarger lens used to make this print', limit_choices_to={'lensmodel__mount__purpose': 'Enlarger'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Lens'),
        ),
    ]
