# Generated by Django 2.2.4 on 2019-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0036_auto_20190924_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='lens_model_compatibility',
            field=models.ManyToManyField(blank=True, to='schema.LensModel'),
        ),
    ]
