# Generated by Django 2.2.4 on 2019-09-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0037_accessory_lens_model_compatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountAdapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_optics', models.BooleanField(help_text='Whether this adapter includes optical elements')),
                ('infinity_focus', models.BooleanField(help_text='Whether this adapter allows infinity focus')),
                ('notes', models.CharField(help_text='Freeform notes', max_length=100)),
                ('camera_mount', models.ForeignKey(help_text='Mount used to attach a camera', on_delete=django.db.models.deletion.CASCADE, related_name='camera_mount', to='schema.Mount')),
                ('lens_mount', models.ForeignKey(help_text='Mount used to attach a lens', on_delete=django.db.models.deletion.CASCADE, related_name='lens_mount', to='schema.Mount')),
            ],
            options={
                'verbose_name_plural': 'mount adapters',
                'ordering': ['camera_mount', 'lens_mount'],
            },
        ),
    ]
