# Generated by Django 2.2.4 on 2019-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0038_mountadapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountadapter',
            name='has_optics',
            field=models.BooleanField(blank=True, help_text='Whether this adapter includes optical elements', null=True),
        ),
        migrations.AlterField(
            model_name='mountadapter',
            name='infinity_focus',
            field=models.BooleanField(blank=True, help_text='Whether this adapter allows infinity focus', null=True),
        ),
        migrations.AlterField(
            model_name='mountadapter',
            name='notes',
            field=models.CharField(blank=True, help_text='Freeform notes', max_length=100, null=True),
        ),
    ]
