# Generated by Django 2.2.4 on 2019-09-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0039_auto_20190924_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='negative',
            name='mount_adapter',
            field=models.ForeignKey(blank=True, help_text='Mount adapter used to mount lens', null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.MountAdapter'),
        ),
    ]
