# Generated by Django 2.2.4 on 2019-09-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0040_negative_mount_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='negative',
            name='copy_of',
            field=models.ForeignKey(blank=True, help_text='Negative that this was duplicated from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy', to='schema.Negative'),
        ),
    ]
