# Generated by Django 2.2.4 on 2019-09-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0041_negative_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='display_lens',
            field=models.OneToOneField(blank=True, help_text='Lens that this camera should be displayed with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_camera', to='schema.Lens'),
        ),
    ]
