# Generated by Django 2.2.4 on 2019-09-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0042_camera_display_lens'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('cameramodel', 'serial')},
        ),
        migrations.AlterUniqueTogether(
            name='lens',
            unique_together={('lensmodel', 'serial')},
        ),
        migrations.AlterUniqueTogether(
            name='negative',
            unique_together={('film', 'frame')},
        ),
        migrations.AlterUniqueTogether(
            name='toning',
            unique_together={('print', 'order')},
        ),
    ]
