# Generated by Django 2.2.12 on 2020-04-29 14:47

from django.db import migrations
import tagging_autocomplete_new.models


class Migration(migrations.Migration):

    replaces = [('schema', '0053_auto_20200428_1316'), ('schema', '0054_auto_20200428_1502'), ('schema', '0055_auto_20200429_1206')]

    dependencies = [
        ('schema', '0052_cameramodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramodel',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='developer',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filmstock',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lensmodel',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mount',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paperstock',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='toner',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
    ]
