# Generated by Django 2.2.12 on 2020-04-28 13:16

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0052_cameramodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramodel',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='developer',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filmstock',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lensmodel',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mount',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paperstock',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='toner',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
