# Generated by Django 2.2.12 on 2020-04-29 12:06

from django.db import migrations
import tagging_autocomplete_new.models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0054_auto_20200428_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameramodel',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='filmstock',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lensmodel',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mount',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paperstock',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='toner',
            name='tags',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, max_length=255),
        ),
    ]
