# Generated by Django 2.2.13 on 2020-07-07 21:25

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0066_historicalbattery_historicaldeveloper_historicalfilmstock_historicalflashprotocol_historicalformat_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramodel',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Image of the camera model', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='historicalcameramodel',
            name='image',
            field=models.TextField(blank=True, help_text='Image of the camera model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallensmodel',
            name='diagram',
            field=models.TextField(blank=True, help_text='Block diagram of the optics', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallensmodel',
            name='image',
            field=models.TextField(blank=True, help_text='Image of the lens model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lensmodel',
            name='diagram',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Block diagram of the optics', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lensmodel',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Image of the lens model', null=True, upload_to='images/'),
        ),
    ]
