# Generated by Django 2.2.14 on 2020-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0076_auto_20200825_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramodel',
            name='date_imprint',
            field=models.BooleanField(blank=True, help_text='Whether the camera has a date imprint feature', null=True),
        ),
        migrations.AddField(
            model_name='historicalcameramodel',
            name='date_imprint',
            field=models.BooleanField(blank=True, help_text='Whether the camera has a date imprint feature', null=True),
        ),
    ]
