# Generated by Django 2.2.14 on 2020-08-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0077_auto_20200825_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramodel',
            name='image_circle',
        ),
        migrations.RemoveField(
            model_name='historicalcameramodel',
            name='image_circle',
        ),
    ]
