# Generated by Django 2.2.17 on 2020-11-26 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schema', '0109_auto_20201126_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teleconverter',
            new_name='TeleconverterModel',
        ),
    ]
