# Generated by Django 3.2.19 on 2023-05-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0134_auto_20230423_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negative',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='Lens used to take this negative', limit_choices_to=models.Q(('lensmodel__mount__purpose', 'Camera')), null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.lens'),
        ),
        migrations.AlterField(
            model_name='print',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='Enlarger lens used to make this print', limit_choices_to=models.Q(('lensmodel__mount__purpose', 'Enlarger')), null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.lens'),
        ),
    ]
